-- MySQL Script generated by MySQL Workbench
-- mié 02 sep 2015 18:03:39 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CIB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CIB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CIB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CIB` ;

-- -----------------------------------------------------
-- Table `CIB`.`Suministro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Suministro` (
  `codigoSuministro` INT NOT NULL,
  `nombreSuministro` VARCHAR(150) NOT NULL,
  `descSuministro` VARCHAR(250) NOT NULL,
  `unidadMedidaSuministro` VARCHAR(45) NOT NULL,
  `cantidadSuministro` INT NOT NULL,
  `tipoSuministro` VARCHAR(45) NOT NULL,
  `estadoSuministro` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`codigoSuministro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Proveedor` (
  `codigoProveedor` INT NOT NULL,
  `nombreProveedor` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`codigoProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Factura_Encabezado_Suministro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Factura_Encabezado_Suministro` (
  `numeroFactura` INT NOT NULL,
  `fechaCompra` DATE NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `codigoProveedor` INT NOT NULL,
  `tipoCompra` VARCHAR(25) NOT NULL,
  `montoTotal` DECIMAL NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`numeroFactura`),
  INDEX `fk_Factura_Encabezado_Suministro_Proveedor1_idx` (`codigoProveedor` ASC),
  CONSTRAINT `fk_Factura_Encabezado_Suministro_Proveedor1`
    FOREIGN KEY (`codigoProveedor`)
    REFERENCES `CIB`.`Proveedor` (`codigoProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Factura_Detalle_Suministro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Factura_Detalle_Suministro` (
  `idFactura_Detalle` INT NOT NULL AUTO_INCREMENT,
  `numeroFacturaEncabezado` INT NOT NULL,
  `codigoSuministro` INT NOT NULL,
  `cantidadSuministro` INT NOT NULL,
  `precioSuministro` DECIMAL NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idFactura_Detalle`),
  INDEX `fk_Factura_Detalle_Suministro_Factura_Encabezado_Suministro_idx` (`numeroFacturaEncabezado` ASC),
  INDEX `fk_Factura_Detalle_Suministro_Suministro1_idx` (`codigoSuministro` ASC),
  CONSTRAINT `fk_Factura_Detalle_Suministro_Factura_Encabezado_Suministro1`
    FOREIGN KEY (`numeroFacturaEncabezado`)
    REFERENCES `CIB`.`Factura_Encabezado_Suministro` (`numeroFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Detalle_Suministro_Suministro1`
    FOREIGN KEY (`codigoSuministro`)
    REFERENCES `CIB`.`Suministro` (`codigoSuministro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Oficina` (
  `idOficina` INT NOT NULL AUTO_INCREMENT,
  `nombreOficina` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idOficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Solicitud_Encabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Solicitud_Encabezado` (
  `numeroSolicitud` INT NOT NULL AUTO_INCREMENT,
  `idOficina` INT NOT NULL,
  `nombreSolicitud` VARCHAR(100) NOT NULL,
  `idUsuario` INT NOT NULL,
  `fechaSolicitud` DATE NOT NULL,
  `cantidadTotal` INT NOT NULL,
  `observacion` MEDIUMTEXT NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`numeroSolicitud`),
  INDEX `fk_Solicitud_Encabezado_Oficina1_idx` (`idOficina` ASC),
  INDEX `fk_Solicitud_Encabezado_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Solicitud_Encabezado_Oficina1`
    FOREIGN KEY (`idOficina`)
    REFERENCES `CIB`.`Oficina` (`idOficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_Encabezado_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `CIB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Solicitud_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Solicitud_Detalle` (
  `idSolicitud_Detalle` INT NOT NULL AUTO_INCREMENT,
  `numeroSolicitud` INT NOT NULL,
  `codigoSuministro` INT NOT NULL,
  `cantidadSolicitud` INT NOT NULL,
  `cantidadEntregada` INT NOT NULL,
  `Solicitud_Encabezado_numeroSolicitud` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idSolicitud_Detalle`, `Solicitud_Encabezado_numeroSolicitud`),
  INDEX `fk_Solicitud_Detalle_Solicitud_Encabezado1_idx` (`numeroSolicitud` ASC),
  INDEX `fk_Solicitud_Detalle_Suministro1_idx` (`codigoSuministro` ASC),
  CONSTRAINT `fk_Solicitud_Detalle_Solicitud_Encabezado1`
    FOREIGN KEY (`numeroSolicitud`)
    REFERENCES `CIB`.`Solicitud_Encabezado` (`numeroSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_Detalle_Suministro1`
    FOREIGN KEY (`codigoSuministro`)
    REFERENCES `CIB`.`Suministro` (`codigoSuministro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Pantalla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Pantalla` (
  `idPantalla` INT NOT NULL AUTO_INCREMENT,
  `Pantallacol` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPantalla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Usuario_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Usuario_Rol` (
  `idUsuario` INT NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRol`),
  INDEX `fk_Usuario_Rol_Rol1_idx` (`idRol` ASC),
  CONSTRAINT `fk_Usuario_Rol_Rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `CIB`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `CIB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Pantalla_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Pantalla_Rol` (
  `idRol` INT NOT NULL,
  `idPantalla` INT NOT NULL,
  INDEX `fk_Pantalla_Rol_Pantalla1_idx` (`idPantalla` ASC),
  CONSTRAINT `fk_Pantalla_Rol_Pantalla1`
    FOREIGN KEY (`idPantalla`)
    REFERENCES `CIB`.`Pantalla` (`idPantalla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pantalla_Rol_Rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `CIB`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CIB`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CIB`.`Bitacora` (
  `idBitacora` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  `fechaInclusion` DATE NOT NULL,
  `nombreTabla` VARCHAR(45) NOT NULL,
  `tipoTransaccion` VARCHAR(1) NOT NULL,
  `valorAnterior` VARCHAR(600) NULL,
  `valorNuevo` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`idBitacora`),
  INDEX `fk_Bitacora_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Bitacora_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `CIB`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
